# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme:            "mmistakes/minimal-mistakes@4.14.1"
minimal_mistakes_skin:   "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale                   : "en"
title                    : "madsdavidsen.com"
title_separator          : "-"
name                     : "madsdavidsen.com"
description              : "Mads is a professional Danish Football Coach. He is currently the Technical Director at the professional Chinese club Shanghai SIPG F.C. Mads holds the highest coaching license in the World - the UEFA PRO coaching license. Mads holds a Master in Journalism & History from Roskilde University in Denmark and a Mini MBA in Leadership & Management from Probana as well."
url                      : "" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "lsolesen/madsdavidsen-com-jekyll" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
staticman:
  branch                 : "gh-pages"
atom_feed:
  path                   : # blank (default) uses feed.xml


# reCaptcha
# Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
reCaptcha:
  enabled: true
  siteKey: "6Ld8IVgUAAAAABlknXDufmeoXE1y11C0CZoXDJbw"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "syc6lZt75LsDkZfXpjD7IhE1bzn7MHPSyf1q2Vbywpl2x0qOWolFXjhYMyZH2wM2+XtnDqaQJezOhq2sOwUxLsY436T2+Ycb9T3yY0sbTE1+LV52bIhFZlzDJ++CIHa8F2o5CfL6/bPVNW8yuQa3TvbBRIUvtY8DQ5HmgopFO38="


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : "MadsRDavidsen"
facebook:
  username               : "Mads.Davidsen1982"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Site search
search: true


# Analytics
analytics:
  provider               : "google-universal" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-39927038-1"


# Site Author
author:
  name             : "Mads Davidsen"
  avatar           : "/assets/images/authors/mads-davidsen.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "UEFA Pro Football Coach | Technical Director at Shanghai SIPG F.C. (China) | Author of With Great Talent Comes Great Responsibility | Key note speaker"
  location         : "Shanghai, China"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://madsdavidsen.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MadsRDavidsen"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/Mads.Davidsen1982"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://dk.linkedin.com/in/mads-davidsen-9007545"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      sidebar:
        nav: "sidebar"
